### ISSUE TITLE
I can't build my app

### ISSUE THREAD

**Issue by codesundar** [codesundar/ionic-uber-clone#4]
Any issue with generating apk?

**Comment by codesundar** [comment]
1. You must built this app via CLI, don't use android studio or cloud build ..etc
2. Please use correct version of npm, node, ionic, cordova-android as mentioned in docs
3. Create any sample project then try to build that sample project
    3.1: If sample project itself is not building, then there is an issue with your ionic environment, please fix that first
    3.2: If sample project is success, then contact me on WhatsApp: https://codesundar.com/contact-us

**How to create a sample project?**
```
ionic start dummy blank
cd dummy
ionic cordova platform add android
ionic cordova build android
```

**Comment by NestorDevs** [comment]
if I run ionic serve works perfect ... now if I run npm run ionic: build --prod gives me the following error

typescript error 
            Type CarsPage in /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 
            (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.ts is part of the declarations of 2 modules: AppModule in 
            /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 (2)/ionTaxi-1.2.3/admin/src/app/app.module.ts and 
            CarsPageModule in /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 
            (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.module.ts! Please consider moving CarsPage in 
            /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.ts to a 
            higher module that imports AppModule in /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 
            (2)/ionTaxi-1.2.3/admin/src/app/app.module.ts and CarsPageModule in /home/neivert/Development/UBER 
            CLONE/ionTaxi-1.2.3 (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.module.ts. You can also create a new 
            NgModule that exports and includes CarsPage in /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 
            (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.ts then import that NgModule in AppModule in 
            /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 (2)/ionTaxi-1.2.3/admin/src/app/app.module.ts and 
            CarsPageModule in /home/neivert/Development/UBER CLONE/ionTaxi-1.2.3 
            (2)/ionTaxi-1.2.3/admin/src/pages/cars/cars.module.ts.

**Comment by FranckEtiam** [comment]
Hi sir,
how did you solve this problem, I am in the same case.
