### ISSUE TITLE
Map is not loading

### ISSUE THREAD

**Issue by codesundar** [codesundar/ionic-uber-clone#8]
My Map is not loading & showing whitescreen

**Comment by codesundar** [comment]
Please refer: #2 

!! important Check
- Have you added geolocation plugin & Whitelist plugin ?? Try to re-add it again (manually)
```
ionic cordova plugin add cordova-plugin-geolocation
ionic cordova plugin add cordova-plugin-whitelist
```

Also Check your location permission

**Comment by Bobkie** [comment]
That is not the reason the map doesn't load, i found the solution to it

**Comment by Jonkred** [comment]
How did you solve this problem?
